name: flutter_train_boarding
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  intl: ^0.19.0
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.5.1
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  cached_network_image: ^3.4.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  font_awesome_flutter: ^10.8.0

  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  http: ^1.2.1
  flutter_cache_manager: ^3.4.1
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  image: "assets/images/ic_launcher.png"
  color: "2e2e2e"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"

adaptive_icon_background: "#2e2e2e"
adaptive_icon_foreground: "assets/imagess/ic_launcher.png"
